uocsecrets/forum/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name = 'forum'
urlpatterns = [

    # /forum/


    path('about/', TemplateView.as_view(template_name='forum/about.html'),name='about'),
    path('', views.IndexView.as_view(), name = 'index'),
    path('top/', views.IndexView.as_view(), name = 'top'),
    path('new/', views.IndexView.as_view(), name = 'new'),
    path('<str:mode>/<int:page>/', views.PageView.as_view(), name = 'page'),

    # /forum/edit/
    path('edit/', views.EditView.as_view(), name = 'new_post'),
    path('<int:post_id>/edit/', views.EditView.as_view(), name='edit'),
    path('<int:post_id>/edit/delete/', views.delete, name='delete'),

    # /forum/<post_id>/
    path('<int:post_id>/', views.ContentView.as_view() , name='content'),
    path('<int:post_id>/clickup/', views.ClickUpView.as_view(), name='clickup'),

    # /forum/<post_id>/comment/
    path('<int:post_id>/comment/', views.CommentView.as_view(), name='new_comment'),
    path('<int:post_id>/comment/<int:comment_id>/', views.CommentView.as_view(), name='comment'),

    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('login/', views.LoginView.as_view(template_name='forum/login.html',
                                           extra_context = {'next': '/forum/'}), name='login'),
    path('logout/', views.LogoutView.as_view(), name = 'logout'),

    # /forum/user/
    path('user/<str:username>/', views.UserView.as_view(), name='user'),
]

uocsecrets/uocsecrets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uocsecrets/forum/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import validate_image_file_extension
import os
from uuid import uuid4


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    user_pk = models.IntegerField(default=0, editable=False)
    clicked = models.TextField(default='', null=True, blank=True)

    @classmethod
    def default_user(cls):
        try: anon = User.objects.get(pk=1)
        except ObjectDoesNotExist:
            anon = Profile.create_user('Anonymous', '', 'Anonymous').user
        return anon


    def is_anon(self):
        return self.user.pk == 1

    @classmethod
    def create_user(cls, username, email, password):
        user = User.objects.create_user(username, email, password)
        return cls.objects.create(user = user, user_pk = user.pk, clicked ='')

    def __str__(self):
        return self.user.username


def rand_path_filename(instance, original_name):
    upload_to = 'post/'
    ext = original_name.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join(upload_to, filename)


class Post(models.Model):
    title = models.CharField(max_length=50, default='Untitled')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default = timezone.now)
    content = models.TextField(default="Whoa such empty")
    clicks = models.IntegerField(default=0)
    tags = models.IntegerField(default=0)
    image = models.ImageField(upload_to=rand_path_filename,
                              validators=[validate_image_file_extension],
                              null=True, blank=True)

    def __str__(self):
        return self.title

    @classmethod
    def get_next_title(self):
        last_post = Post.objects.last()
        if last_post:
            return 'Secret #'+str(last_post.id+1)
        else: return 'Secret #1'







class Comments(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=50, default='')
    date = models.DateTimeField(default=timezone.now)
    content = models.TextField(default='')
    # if a post gets deleted, the comments will also be deleted (SQL CASCADE DELETE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # recursive model relationship
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    @classmethod
    def new_display_name(self, request, data):
        last_comment = Comments.objects.last()
        if last_comment:
            last_comment_id = last_comment.id
        else: last_comment_id = 0
        if request.user.is_authenticated:
            return '#' + str(last_comment_id + 1) + request.user.username
        else: return '#'+str(last_comment_id + 1) + ' '+ 'User'

    def __str__(self):
        name = self.display_name + ' : ' + str(self.content)[:30]
        if len(name) >= 29:
            name += '...'
        return name

uocsecrets/forum/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View as BaseView
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .form import *
from django.contrib.auth import views as auth_views


from warnings import warn

# TODO: implement password change/reset page


class View(BaseView):

    def get_user(self, request):
        if request.user.is_authenticated:
            return request.user
        else: return Profile.default_user()

class IndexView(View):
    template_name = 'base.html'
    def get(self, request):
        return render(request, self.template_name)

class PageView(View):
    template_name = "forum/page.html"

    def get_clicked(self, request, post_id):
        if request.user.is_authenticated:
            clicked_list = request.user.profile.clicked.split()
        else:
            try:
                clicked_list = request.session['clicked'].split()
            except KeyError: return False
        return str(post_id) in clicked_list


    def get(self, request, page, mode):
        user = request.user
        post_per_page = 15
        post_range_start = (page-1)*post_per_page
        post_range_end = page * post_per_page
        if mode == 'top':
            self.index_post = list(Post.objects.order_by('-clicks'))[post_range_start:post_range_end]
        else:
            self.index_post = Post.objects.order_by('-date')[post_range_start:post_range_end]

        #self.index_post = Post.objects.order_by('-date')[post_range_start:post_range_end]

        for this_post in self.index_post:
            this_post.comment_snaps = Comments.objects.filter(post=this_post)[:3]
            this_post.clicked = self.get_clicked(request, this_post.pk)
        context = {
            'user':user,
            'latest_post_list': self.index_post,
        }
        return render(request, self.template_name, context)


class EditView(View):
    # parameter from LoginRequiredMixin to redirect to login page
    #login_url = '/forum/login/'

    form_class = PostForm
    template_name = 'forum/edit.html'
    action = '/edit/'

    def get_post_data(self, post_id):
        if post_id:
            self.action = '/' + str(post_id) + '/edit/'
            self.current_post = get_object_or_404(Post, pk=post_id)
            return {
            'title' : self.current_post.title,
            'content' : self.current_post.content,
        }
        else:
            return {'title':'', 'content':''}

    def get_post_title(self, request, data):
        if data['title']:
            title = data['title']
        elif data['display_name']:
            title = request.user.username
        else:
            title = Post.get_next_title()
        return title

    def get(self, request, post_id=0):
        initial = self.get_post_data(post_id)
        form = self.form_class(initial)
        return render(request, self.template_name,
                      {
                        'action' : self.action,
                        'form': form,
                        'post_id': post_id,
                      })

    def post(self, request, post_id=0):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            if post_id:
                self.current_post = get_object_or_404(Post, pk=post_id)
                if data['title']: self.current_post.title=data['title']
                self.current_post.content = data['content']
                self.current_post.save()
            else:
                Post.objects.create(title=self.get_post_title(request, data),
                                    content=data['content'],
                                    author=self.get_user(request),
                                    image=request.FILES.get('image', None))
        return HttpResponseRedirect('/')


def delete(request, post_id):
    if post_id:
        Post.objects.get(pk=post_id).delete()
    return HttpResponseRedirect('/')


class ClickUpView(View):
    def check_user_clicked(self, post_id, user):
        clicked_list = user.profile.clicked.split()
        if str(post_id) in clicked_list:
            clicked_list.remove(str(post_id))
            user.profile.clicked = ' '.join(clicked_list)
            user.profile.save()
            return True
        else:
            clicked_list.append(str(post_id))
            user.profile.clicked = ' '.join(clicked_list)
            user.profile.save()
            return False

    def check_anon_clicked(self, post_id, session):
        try:
            clicked_list = session['clicked'].split()
        except KeyError:
            session['clicked']=''
            clicked_list = session['clicked'].split()
        if str(post_id) in clicked_list:
            clicked_list.remove(str(post_id))
            session['clicked'] = ' '.join(clicked_list)
            session.save()
            return True
        else:
            clicked_list.append(str(post_id))
            session['clicked'] = ' '.join(clicked_list)
            session.save()
            return False

    def clickup(self, object, post_id, post, check_method):
        if check_method(post_id, object):
            post.clicks-=1
            post.save()
            return JsonResponse({'clicks' : post.clicks, 'clicked' : False})
        else:
            post.clicks+=1
            post.save()
            return JsonResponse({'clicks' : post.clicks, 'clicked' : True})

    def get(self, request, post_id):
        this_post = Post.objects.get(pk=post_id)
        user = request.user
        if request.user.is_authenticated:
            return self.clickup(user, post_id, this_post, self.check_user_clicked)
        else: return self.clickup(request.session, post_id, this_post, self.check_anon_clicked)


class ContentView(View):
    template_name = 'forum/content.html'

    def get(self, request, post_id=0):
        this_post = get_object_or_404(Post, pk=post_id)
        context = {
            'list_of_comments':Comments.objects.filter(post = this_post),
            'form': CommentForm(),
            'post': this_post,
        }
        return render(request, self.template_name, context)


class CommentView(View):
    template_name = 'forum/content.html'

    def post(self, request, post_id, comment_id=0):
        this_post = get_object_or_404(Post, pk=post_id)
        replay_to = None
        if comment_id:
            replay_to = get_object_or_404(Comments, pk=comment_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            Comments.objects.create(content=data['content'],
                                    parent_comment=replay_to,
                                    post=this_post,
                                    author=self.get_user(request),
                                    display_name=Comments.new_display_name(request, data))
        context = {
            'list_of_comments':Comments.objects.filter(post = this_post),
            'form': CommentForm(),
            'post': this_post,
        }
        return render(request, self.template_name, context)


class UserView(View):
    pass


class SignUpView(View):
    form_class = SignupForm
    template_name = 'forum/signup.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            Profile.create_user(
                data['username'],
                data['email'],
                data['password']
            )
        return HttpResponseRedirect('/')




class LoginView(auth_views.LoginView):
    pass



class LogoutView(auth_views.LogoutView):
    pass

uocsecrets/ui/templates/forum/about.html
{% load static %}
<div class="block-container d-flex justify-content-center">
  <div class="card content-card">
    <div class="card-body">
      <img src="{% static "assets/hello_there.jpg" %}" style="width:100%;"/>
      <p>

        Welcome to UoCSecret!
      </p>
      <p>
        uocsecret.com is a anonymous social website risen from the ashes of our beloved Facebook page UChicago Secrets, but with more fun stuff and less censorship crap.
      </p>
      <p>
        This website is created and run entirely by UChicago college students (one so far). Currently it is only known to a small number of people, most of whom trusted fellow students. It is my hope that this website will reach further into the student body and enrich our barren life of the mind.
      </p>
      <p>
        Should you have any suggestion or bug report, feel free to <a href="mailto:uocsecret@gmail.com">shoot me an email</a> or just dm me on WeChat. Any technical feedback, especially regarding UI/UX, is welcomed.
      </p>
      <p>
        This website is hand-crafted using the Django framework, some jQuery libraries and an unholy amount of Teamo jasmine milktea. If you are intested in joining me to make uocsecret great again, email/dm me for access to the git repo.
      </p>
      <p>
        Finally, remember to be kind to each other and have fun!
      </p>
      <div style="text-align: right;">
        <p>
          admin
        </p>
        <p>
          Sep 25, 2018
        </p>
      </div>

      <div>
        <p>
          Known bug(s):
        </p>
        <ol>
          <li>
            Posts sometimes overlap after first load (Solution: try reload or scroll to the bottom then scroll up)
          </li>
          <li>
            Sometimes (1/20) image upload fails (Currently working out solution)
          </li>
        </ol>
      </div>


    </div>
  </div>
</div>

uocsecrets/ui/templates/forum/content.html
{% load widget_tweaks %}
{% load static %}

<script>
$(document).ready(function() {
  $(".comment-form").submit(function(e) {
    e.preventDefault();
    post_url = ["/", $(this).attr('id'), "/"].join('');
    comment_url = post_url.concat('comment/');
    $.ajax({
      url: comment_url,
      data: {
        content: $("#contentTextArea").val(),
        csrfmiddlewaretoken: '{{ csrf_token }}',
      },
      type: "POST",
      success: function(data) {
       $("#content-overlay").load(post_url);
      },
      error: function(xhr, ajaxOptions, thrownError) {
        alert(xhr.status);
        alert(thrownError);
      },
    })
  });

  $(".content-card-close-icon").click(function() {
    $("#content-overlay").html('');
  });

  // $(".content-card-image").click(function() {
  //   $(".content-image-overlay").load(
  //     $(".content-card-image").attr('src'), function(){
  //       $('*').click(function(){
  //         $(".content-card-image").html('');
  //       });
  //     });
  // });
});
</script>

<div class="block-container d-flex justify-content-center">
  <div class="card content-card">
    <div class="card-body">

      <div class="index-top-container">
        <img class="index-card-top index-card-profile" src="{% static "assets/secret-icon-1.png" %}"/>
        <h6 class="index-card-title index-card-top">{{ post.title }}</h6>
        <p class="index-card-top index-card-date">{{ post.date }}</p>
        <img class="content-card-close-icon index-card-top" src="{% static "assets/close-icon.png" %}"/>
      </div>

      <p class="card-button-right">
        {% if user.is_superuser %}
        <a href="{% url 'forum:edit' post.id %}">Edit</a>
        {% endif %}
      </p>

      {% if post.image %}
      <img class="content-card-image" src="{{ post.image.url }}"/>
      <div class="content-image-overlay"></div>
      {% endif %}


      <p class="card-text index-card-text">{{ post.content|linebreaks }}</p>


      <ul class="list-group list-group-flush">
        {% if list_of_comments %}
        {% for comment in list_of_comments %}
        <li class="list-group-item">
          {{ comment.display_name }} : {{ comment.content }}
        </li>
        {% endfor %}
        {% else %}
        <p class="card-text">Be the first one to comment!</p>
        {% endif %}
      </ul>




      <div class="card-body">
        <form class="comment-form" id="{{ post.id }}">
          {% csrf_token %}
          <div class="form-group">
            <label for="contentTextArea">Comment</label>
            {% render_field form.content class="form-control comment-form" id="contentTextArea" %}
            {% if user.is_authenticated %}
            {% render_field form.display_name class="form-check-input" id="displayNameChoice" style="width: auto"%}
            <label class="form-check-label" for="displayNameChoice">Use username?</label>
            {% endif %}
          </div>
          <button class="btn btn-primary" >Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

uocsecrets/ui/templates/forum/edit.html
{% load widget_tweaks %}
{% load static %}

<script>
$(document).ready(function() {
  $(".content-card-close-icon").click(function() {
    $("#content-overlay").html('');
  });
});
</script>

<div class="block-container d-flex justify-content-center">
  <div class="card content-card" id="content-card-id">
    <div class="card-body">

<div>
      {% if user.is_superuser %}
      <h5 class="card-title">Edit Post</h5>
      <p><a href="{% url 'forum:delete' post_id %}">Delete</a></p>
      {% else %}
      <h5 class="card-title">Post a secret...</h5>
      {% endif %}
      <img class="content-card-close-icon" src="{% static "assets/close-icon.png" %}"/>
    </div>

      <div class="card-body">
        <form enctype="multipart/form-data" action="{{ action }}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="contentTextArea">Write down your secret...</label>
            {% render_field form.content class="form-control" id="contentTextArea" %}
            <label for="contentImage">Image (Optional)</label>
            {% render_field form.image class="form-control" id="contentImage" %}
            {% if user.is_authenticated %}
            {% render_field form.display_name class="form-check-input" id="displayNameChoice" style="width: auto"%}
            <label class="form-check-label" for="displayNameChoice">Use username?</label>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>


<!--



-->

uocsecrets/ui/templates/forum/login.html
{% extends 'base.html' %}
{% block content %}


{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% comment %}
{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}
{% endcomment %}

<form method="post" action="{% url 'forum:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{% comment %}<p><a href="{% url 'password_reset' %}">Lost password?</a></p>{% endcomment %}

{% endblock %}

uocsecrets/ui/templates/forum/page.html
{% load static %}
<script>
    function reload_js(src) {
        $('script[src="' + src + '"]').remove();
        $('<script>').attr('src', src).appendTo('head');
    }
      reload_js("{% static "base.js" %}");
      // console.log("re-attatched base.js");
</script>
    {% for post in latest_post_list %}
    <div class="card my-2 mx-2 grid-item index-card">
      <div class="card-body card-body-ajax" id="{{ post.id }}">
        <div class="index-top-container">
          <img class="index-card-top index-card-profile" src="{% static "assets/secret-icon-1.png" %}"/>
          <h6 class="index-card-title index-card-top">{{ post.title }}</h6>
          <p class="index-card-top index-card-date">{{ post.date }}</p>
        </div>
        <div class="card-text index-card-text">
        {% if post.image %}
        <img class="index-card-image" src="{{ post.image.url }}" />
        {% endif %}
        {{ post.content|linebreaks }}
      </div>
      </div>
      <ul class="list-group list-group-flush">
        {% for comment_snippet in post.comment_snaps %}
        <li class="list-group-item index-card-comment">{{comment_snippet}}</li>
        {% endfor %}
      </ul>
      <div class="card-body card-bot row">
        {% if post.clicked %}
        <p class="card-button-bot clickup-button-ajax clickup-clicked col" id='{{ post.id }}'>
          Upvote {{post.clicks}}</p>
        {% else %}
        <p class="card-button-bot clickup-button-ajax clickup-unclicked col" id='{{ post.id }}'>
          Upvote {{post.clicks}}
        </p>
        {% endif %}
        <p class="card-button-bot comment-ajax comment-button col" id='{{ post.id }}'>Comment</p>
        <!-- <p class="card-button-bot tag-ajax tag-button col">Tag {{post.tags}}</p> -->
      </div>
    </div>
    {% endfor %}

uocsecrets/ui/templates/forum/signup.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'forum:sign_up' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

uocsecrets/ui/templates/forum/user.html
{% extends 'base.html' %}
{% block content %}

<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Date created: {{ user.date_joined }}</p>

{% endblock  %}