uocsecrets/forum/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name = 'forum'
urlpatterns = [

    # /forum/


    path('about/', TemplateView.as_view(template_name='forum/about.html'),name='about'),
    path('', views.IndexView.as_view(), name = 'index'),
    path('top/', views.IndexView.as_view(), name = 'top'),
    path('new/', views.IndexView.as_view(), name = 'new'),
    path('<str:mode>/<int:page>/', views.PageView.as_view(), name = 'page'),

    # /forum/edit/
    path('edit/', views.EditView.as_view(), name = 'new_post'),
    path('<int:post_id>/edit/', views.EditView.as_view(), name='edit'),
    path('<int:post_id>/edit/delete/', views.delete, name='delete'),

    # /forum/<post_id>/
    path('<int:post_id>/', views.ContentView.as_view() , name='content'),
    path('<int:post_id>/clickup/', views.ClickUpView.as_view(), name='clickup'),

    # /forum/<post_id>/comment/
    path('<int:post_id>/comment/', views.CommentView.as_view(), name='new_comment'),
    path('<int:post_id>/comment/<int:comment_id>/', views.CommentView.as_view(), name='comment'),

    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('login/', views.LoginView.as_view(template_name='forum/login.html',
                                           extra_context = {'next': '/forum/'}), name='login'),
    path('logout/', views.LogoutView.as_view(), name = 'logout'),

    # /forum/user/
    path('user/<str:username>/', views.UserView.as_view(), name='user'),
]

uocsecrets/uocsecrets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uocsecrets/ui/templates/base.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title id=''>UoCSecret</title>
  <link rel="shortcut icon" type="image/x-icon" href="{% static "assets/secret-icon-1.png" %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "base.css" %}">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
  <!-- <script src="{% static "base.js" %}"></script> -->
  <script>
    $(window).on("load", function() {
      url  = window.location.href.slice(-4,-1);
      if (url==='top') {
        $('title').attr('id', 'top');
      } else {
          $('title').attr('id', 'new');
      }
      load_url = ['/',$('title').attr('id'),'/1/'].join('');
      $('.page-container').load(load_url, function(){
        // console.log('first page loaded');
        $('.grid').masonry();
      });
    });
  </script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="UoCSecret">
</head>

<body>
  <div class="container-fluid grand-container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'forum:index' %}">UoCSecret</a>
      <button
      class="navbar-toggler collapsed"
      type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'forum:top' %}">Top</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'forum:new' %}">New</a>
          </li>
          <li class="nav-item">
            <a class="nav-link about-ajax">About</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link new-post-ajax">New Post</a>
          </li>
          <!--
          {% if user.is_authenticated %}
          {{ user.username }}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'forum:logout'%}">Log out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'forum:login'%}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'forum:sign_up'%}">Sign up</a>
          </li>
          {% endif %}
        -->
        </ul>
      </div>
    </nav>
    <div id="content-overlay"></div>
    <div class="container-fluid index-container">
      <div class="grid page-container" id=1></div>
    </div>
    <div class="loading-text">Loading next page...</div>

  </div>


</body>

</html>